/**
 * config — 중앙 설정 모듈
 * 매직 넘버를 하나의 불변 객체로 관리한다.
 */

export const config = Object.freeze({
  convergence: Object.freeze({ threshold: 0.8, maxRounds: 3, earlyExitThreshold: 0.85 }),
  discussion: Object.freeze({
    parallelTiers: true,
    maxReviewers: 3,
    reviewModel: 'haiku',
    stagnationThreshold: 0.05,
    compressMaxLength: 2000,
    keyDecisionMaxLength: 1200,
    minCompressedLength: 200,
    defaultPriority: 5,
    tierBounds: Object.freeze([2, 4, 7]),
  }),
  messaging: Object.freeze({
    enabled: false,
    maxMessages: 100,
    ttl: 86400,
    maxThreadDepth: 5,
  }),
  similarity: Object.freeze({
    redundancyThreshold: 0.7,
    contributionThreshold: 0.5,
    criticalWeight: 3,
    emptyReviewPenalty: -0.5,
  }),
  execution: Object.freeze({
    maxFixAttempts: 2,
    maxEscalationAttempts: 3,
    maxOutputLines: 200,
    maxAgentCalls: 500,
    reviewIntervention: false,
  }),
  build: Object.freeze({ defaultTimeout: 30_000, goTimeout: 45_000, javaTimeout: 60_000 }),
  llm: Object.freeze({
    defaultTimeout: 60_000,
    defaultMaxTokens: 4096,
    pingTimeout: 15_000,
    pingMaxTokens: 16,
    maxRetries: 3,
    maxPromptSectionLength: 3000,
  }),
  review: Object.freeze({
    minReviewers: 2,
    maxReviewers: 3,
    maxRevisionRounds: 2,
    maxImportantIssues: 10,
    fatiguePenalty: 0.5,
  }),
  quality: Object.freeze({
    criticalPenalty: 20,
    importantPenalty: 5,
    fixAttemptPenalty: 10,
    buildFailurePenalty: 30,
    firstPhaseWeight: 0.3,
  }),
  evolution: Object.freeze({
    targetScore: 80,
    maxGenerations: 3,
    minImprovement: 5,
  }),
  team: Object.freeze({
    simple: Object.freeze({ min: 2, max: 3 }),
    medium: Object.freeze({ min: 3, max: 5 }),
    complex: Object.freeze({ min: 5, max: 8 }),
  }),
  recommendation: Object.freeze({
    minScore: 3,
    maxPerCategory: 5,
    maxKeywordHits: 3,
    weights: Object.freeze({ projectType: 3, complexity: 2, keyword: 1, roleAffinity: 2 }),
  }),
  github: Object.freeze({
    enabled: false,
    branchStrategy: 'timestamp',
    baseBranch: 'main',
    autoPush: true,
    autoCreatePR: true,
    prDraft: false,
    worktreeIsolation: false,
  }),
  clarity: Object.freeze({
    threshold: 0.8,
    minImprovement: 0.05,
    maxDescriptionLength: 3000,
    dimensionThreshold: 0.6,
  }),
  taskClassification: Object.freeze({
    engineerRoles: Object.freeze(['backend', 'frontend', 'fullstack', 'devops', 'data']),
    codeDomains: Object.freeze(['frontend', 'backend', 'api', 'database', 'fullstack']),
    koreanKeywords: Object.freeze(['구현', '개발', '코딩']),
    englishKeywords: Object.freeze([
      'implement',
      'implements',
      'implementation',
      'develop',
      'developer',
      'code',
      'coding',
      'build',
      'builds',
      'create',
      'creates',
      'api',
      'apis',
      'endpoint',
      'endpoints',
      'component',
      'components',
      'function',
      'functions',
      'module',
      'modules',
      'class',
      'classes',
      'service',
      'services',
      'controller',
      'controllers',
      'middleware',
      'route',
      'routes',
      'router',
      'schema',
      'schemas',
      'migration',
      'migrations',
      'test',
      'tests',
      'testing',
      'spec',
      'specs',
    ]),
  }),
  cli: Object.freeze({ suggestionThreshold: 3, maxInputLength: 50 }),
  pr: Object.freeze({ maxTitleLength: 70 }),
  commit: Object.freeze({ maxSubjectLength: 72 }),
  http: Object.freeze({
    retryableCodes: Object.freeze([429, 500, 502, 503, 504]),
    errorTruncateLength: 200,
    maxRetryDelay: 8000,
    retryJitter: 200,
  }),
  ciVersions: Object.freeze({
    python: Object.freeze(['3.10', '3.11', '3.12']),
    node: Object.freeze(['18', '20', '22']),
    go: '1.21',
    java: '17',
  }),
  codebase: Object.freeze({
    maxDepth: 10,
    ignoredDirs: Object.freeze([
      'node_modules',
      '.git',
      '.svn',
      'dist',
      'build',
      'coverage',
      '__pycache__',
      '.next',
      '.nuxt',
      'vendor',
      'target',
      '.gradle',
    ]),
    techStackMap: Object.freeze({
      react: 'frontend',
      vue: 'frontend',
      angular: 'frontend',
      svelte: 'frontend',
      nextjs: 'frontend',
      express: 'backend',
      fastapi: 'backend',
      django: 'backend',
      flask: 'backend',
      nestjs: 'backend',
      koa: 'backend',
      gin: 'backend',
      spring: 'backend',
      docker: 'devops',
      kubernetes: 'devops',
      terraform: 'devops',
      tensorflow: 'data',
      pytorch: 'data',
      pandas: 'data',
    }),
  }),
  report: Object.freeze({ maxTextLength: 100_000, maxEnvLines: 100 }),
});
