#!/usr/bin/env bash
# phase4-report.sh — 보고서 + 텔레그램 알림 + 히스토리 기록 + 정리
# 오케스트레이터에서 source 해서 호출

run_phase4() {
  log_phase "Phase4" "=== 보고서 + 알림 시작 ==="

  local pr_number
  pr_number=$(read_file_or_default "${RUN_DIR}/pr-number" "")
  local pr_url
  pr_url=$(read_file_or_default "${RUN_DIR}/pr-url" "")
  local review_status
  review_status=$(read_file_or_default "${RUN_DIR}/review-status" "UNKNOWN")
  local fix_cycles
  fix_cycles=$(read_file_or_default "${RUN_DIR}/fix-cycle-count" "0")
  local run_date
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')

  # ── 메트릭 수집 ───────────────────────────────────────
  local issue_count=0
  if [[ -f "${RUN_DIR}/issues-created.txt" ]]; then
    issue_count=$(wc -l < "${RUN_DIR}/issues-created.txt" | tr -d ' ')
  fi

  local commit_count=0
  commit_count=$(git log "${BASE_BRANCH}..HEAD" --oneline 2>/dev/null | wc -l | tr -d ' ')

  local file_count=0
  file_count=$(git diff --name-only "${BASE_BRANCH}..HEAD" 2>/dev/null | wc -l | tr -d ' ')

  # 카테고리 수집
  local categories="[]"
  if [[ -f "${RUN_DIR}/issues-created.txt" ]]; then
    local cats
    cats=$(while read -r num; do
      gh issue view "$num" --json labels --jq '.labels[].name' 2>/dev/null
    done < "${RUN_DIR}/issues-created.txt" | grep -E '^(quality|security|performance)$' | sort -u | paste -sd ',' - 2>/dev/null || echo "")

    if [[ -n "$cats" ]]; then
      categories=$(echo "$cats" | sed 's/^/["/;s/$/"]/' | sed 's/,/","/g')
    fi
  fi

  # metrics.json 생성
  cat > "${RUN_DIR}/metrics.json" <<EOF
{
  "date": "${run_date}",
  "prNumber": ${pr_number:-null},
  "prUrl": "${pr_url}",
  "issues": ${issue_count},
  "commits": ${commit_count},
  "files": ${file_count},
  "reviewStatus": "${review_status}",
  "fixCycles": ${fix_cycles},
  "categories": ${categories}
}
EOF

  log_phase "Phase4" "메트릭: issues=${issue_count}, commits=${commit_count}, files=${file_count}, review=${review_status}"

  # ── 히스토리 기록 ─────────────────────────────────────
  local approved_val="null"
  case "$review_status" in
    APPROVED) approved_val="true" ;;
    CHANGES_REQUESTED) approved_val="false" ;;
  esac

  append_history "$run_date" "$issue_count" "$categories" "$approved_val" "$fix_cycles" "$pr_url"
  log_phase "Phase4" "히스토리 기록 완료"

  # ── PR body 업데이트 ──────────────────────────────────
  if [[ -n "$pr_number" ]]; then
    local pr_body
    pr_body=$(cat <<BODY_EOF
## Daily Improvement 실행 결과

| 항목 | 값 |
|------|-----|
| 실행일 | ${run_date} |
| 이슈 | ${issue_count}건 |
| 커밋 | ${commit_count}건 |
| 변경 파일 | ${file_count}개 |
| 리뷰 상태 | ${review_status} |
| 수정 사이클 | ${fix_cycles}회 |

## CEO 체크리스트

- [ ] 변경사항 확인
- [ ] 이슈 목록 검토
- [ ] 테스트 통과 확인
- [ ] 머지 승인

---
🤖 Generated by Daily Improvement Pipeline
BODY_EOF
)

    gh pr edit "$pr_number" --body "$pr_body" >> "$LOG_FILE" 2>&1 || true

    # ── 라벨 추가 ────────────────────────────────────────
    if [[ "$review_status" == "APPROVED" ]]; then
      gh pr edit "$pr_number" --add-label "merge-ready" >> "$LOG_FILE" 2>&1 || true
      log_phase "Phase4" "merge-ready 라벨 추가"
    fi
  fi

  # ── 텔레그램 알림 ─────────────────────────────────────
  case "$review_status" in
    APPROVED)
      send_telegram "✅" "리뷰 승인됨 — 머지해주세요
이슈: ${issue_count}건 | 파일: ${file_count}개
PR: ${pr_url}"
      ;;
    CHANGES_REQUESTED)
      if [[ "$fix_cycles" -ge "$MAX_FIX_CYCLES" ]]; then
        send_telegram "⚠️" "수동 확인 필요 — ${MAX_FIX_CYCLES}회 수정 후 미승인
이슈: ${issue_count}건 | 파일: ${file_count}개
PR: ${pr_url}"
      else
        send_telegram "⚠️" "리뷰 미통과 — 수동 확인 필요
PR: ${pr_url}"
      fi
      ;;
    *)
      send_telegram "ℹ️" "파이프라인 완료 (리뷰 상태: ${review_status})
이슈: ${issue_count}건 | PR: ${pr_url}"
      ;;
  esac

  # ── 로그 정리 ─────────────────────────────────────────
  if [[ -n "${LOG_DIR:-}" && -d "${LOG_DIR:-}" ]]; then
    find "$LOG_DIR" -name "*.log" -mtime +30 -delete 2>/dev/null || true
  fi

  log_phase "Phase4" "=== 보고서 + 알림 완료 ==="
  return 0
}

# ── 발견 없음 시 정리 함수 ───────────────────────────────
run_phase4_no_findings() {
  log_phase "Phase4" "=== 발견 없음 정리 ==="

  local run_date
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')

  # 히스토리에 빈 실행 기록
  append_history "$run_date" "0" "[]" "null" "0" "null"

  # 브랜치 삭제
  if [[ -n "${BRANCH_NAME:-}" ]]; then
    log_phase "Phase4" "발견 없음 — 브랜치 삭제: ${BRANCH_NAME}"
    delete_branch "$BRANCH_NAME" 2>/dev/null || true
  fi

  # 로그 정리
  if [[ -n "${LOG_DIR:-}" && -d "${LOG_DIR:-}" ]]; then
    find "$LOG_DIR" -name "*.log" -mtime +30 -delete 2>/dev/null || true
  fi

  log_phase "Phase4" "=== 발견 없음 정리 완료 ==="
}

# ── 에러 시 정리 함수 ────────────────────────────────────
run_phase4_error() {
  local error_msg="${1:-알 수 없는 에러}"
  log_phase "Phase4" "=== 에러 정리: ${error_msg} ==="

  local run_date
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')

  local pr_url
  pr_url=$(read_file_or_default "${RUN_DIR}/pr-url" "없음")

  # 히스토리 기록
  append_history "$run_date" "0" "[]" "null" "0" "null"

  # 텔레그램 알림
  send_telegram "🚨" "파이프라인 에러: ${error_msg}
PR: ${pr_url}
로그: ${LOG_FILE}"

  # 로그 정리
  if [[ -n "${LOG_DIR:-}" && -d "${LOG_DIR:-}" ]]; then
    find "$LOG_DIR" -name "*.log" -mtime +30 -delete 2>/dev/null || true
  fi

  log_phase "Phase4" "=== 에러 정리 완료 ==="
}
