import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  buildPRTitle,
  buildPRBody,
  buildPRLabels,
  createPullRequest,
  buildMergeReport,
  finalizeWithPR,
} from '../scripts/lib/project/pr-manager.js';
import { execFileSync } from 'child_process';

vi.mock('child_process', () => ({
  execFileSync: vi.fn(),
}));

describe('pr-manager', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('buildPRTitle', () => {
    it('프로젝트명을 포함한 PR 제목을 생성한다', () => {
      const title = buildPRTitle({ name: '팀 관리 웹앱' });
      expect(title).toContain('팀 관리 웹앱');
      expect(title).toContain('[GoodVibe]');
    });

    it('커스텀 제목을 지정할 수 있다', () => {
      const title = buildPRTitle({ name: 'test' }, { customTitle: 'feat: add auth' });
      expect(title).toBe('feat: add auth');
    });

    it('70자 이하로 유지한다', () => {
      const title = buildPRTitle({
        name: '매우 긴 프로젝트 이름인데 이것은 정말로 아주 매우 길어서 잘려야 합니다',
      });
      expect(title.length).toBeLessThanOrEqual(70);
    });
  });

  describe('buildPRBody', () => {
    it('프로젝트 요약을 포함한 마크다운을 생성한다', () => {
      const project = {
        name: '팀 관리 웹앱',
        mode: 'plan-execute',
        team: [{ roleId: 'cto' }, { roleId: 'backend' }, { roleId: 'qa' }],
      };
      const executionState = {
        completedPhases: [1, 2, 3],
        phaseResults: {
          1: { taskResults: [{}, {}], qualityGate: { criticalCount: 0, importantCount: 1 } },
          2: { taskResults: [{}], qualityGate: { criticalCount: 0, importantCount: 2 } },
          3: { taskResults: [{}, {}, {}], qualityGate: { criticalCount: 0, importantCount: 0 } },
        },
      };

      const body = buildPRBody(project, executionState);
      expect(body).toContain('## [GoodVibe]');
      expect(body).toContain('plan-execute');
      expect(body).toContain('3개 완료');
      expect(body).toContain('cto');
      expect(body).toContain('Generated by good-vibe');
    });

    it('빈 Phase 결과에도 동작한다', () => {
      const project = { name: 'test', mode: 'quick-build', team: [] };
      const executionState = { completedPhases: [], phaseResults: {} };
      const body = buildPRBody(project, executionState);
      expect(body).toContain('[GoodVibe]');
    });

    it('executionState가 없어도 동작한다', () => {
      const body = buildPRBody({ name: 'test', mode: 'plan-only', team: [] });
      expect(body).toContain('[GoodVibe]');
    });
  });

  describe('buildPRLabels', () => {
    it('프로젝트 모드를 라벨에 포함한다', () => {
      const labels = buildPRLabels({ mode: 'plan-execute', type: 'web-app' });
      expect(labels).toContain('good-vibe');
      expect(labels).toContain('plan-execute');
    });

    it('프로젝트 타입을 라벨에 포함한다', () => {
      const labels = buildPRLabels({ mode: 'quick-build', type: 'telegram-bot' });
      expect(labels).toContain('telegram-bot');
    });

    it('빈 프로젝트에도 기본 라벨을 반환한다', () => {
      const labels = buildPRLabels({});
      expect(labels).toContain('good-vibe');
    });
  });

  describe('createPullRequest', () => {
    it('gh pr create를 실행하고 URL을 반환한다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/42\n');

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/my-branch',
        baseBranch: 'main',
        title: '[GoodVibe] 팀 관리 웹앱',
        body: '## Summary\n...',
      });

      expect(result.success).toBe(true);
      expect(result.url).toBe('https://github.com/user/repo/pull/42');
      expect(result.skipped).toBe(false);
    });

    it('draft PR을 생성할 수 있다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/43\n');

      createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
        draft: true,
      });

      expect(execFileSync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['--draft']),
        expect.any(Object),
      );
    });

    it('라벨을 포함할 수 있다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/44\n');

      createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
        labels: ['good-vibe', 'plan-execute'],
      });

      expect(execFileSync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['--label', 'good-vibe,plan-execute']),
        expect.any(Object),
      );
    });

    it('gh 미설치 시 skipped를 반환한다', () => {
      execFileSync.mockImplementation(() => {
        const err = new Error('gh not found');
        err.code = 'ENOENT';
        throw err;
      });

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
      });

      expect(result.success).toBe(true);
      expect(result.skipped).toBe(true);
      expect(result.reason).toContain('gh');
    });

    it('기타 gh 에러 시 실패를 반환한다', () => {
      execFileSync.mockImplementation(() => {
        const err = new Error('permission denied');
        err.stderr = Buffer.from('not authorized');
        throw err;
      });

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
      });

      expect(result.success).toBe(false);
      expect(result.skipped).toBe(false);
    });
  });

  describe('buildMergeReport', () => {
    const baseProject = {
      name: '팀 관리 웹앱',
      mode: 'plan-execute',
      team: [{ roleId: 'cto' }, { roleId: 'backend' }, { roleId: 'qa' }],
    };

    const baseExecutionState = {
      mode: 'auto',
      startedAt: '2026-03-03T10:00:00Z',
      completedAt: '2026-03-03T12:00:00Z',
      completedPhases: [1, 2],
      phaseResults: {
        1: {
          taskResults: [{}, {}, {}],
          qualityGate: { passed: true, criticalCount: 0, importantCount: 1 },
          reviews: [
            { reviewerId: 'qa', issues: [{ severity: 'important' }], approved: true },
            { reviewerId: 'cto', issues: [], approved: true },
          ],
        },
        2: {
          taskResults: [{}, {}],
          qualityGate: { passed: true, criticalCount: 0, importantCount: 0 },
          reviews: [
            { reviewerId: 'qa', issues: [], approved: true },
            { reviewerId: 'security', issues: [], approved: true },
          ],
        },
      },
      journal: [
        { action: 'execute-tasks', phase: 1 },
        { action: 'quality-gate', phase: 1 },
        { action: 'commit', phase: 1 },
        { action: 'build-context', phase: 1 },
        { action: 'execute-tasks', phase: 2 },
        {
          action: 'quality-gate',
          phase: 2,
          failureSummary: { issueCount: 1, categories: ['logic'] },
        },
        { action: 'fix', phase: 2, fixAttempt: 1 },
        { action: 'quality-gate', phase: 2 },
        { action: 'commit', phase: 2 },
        { action: 'build-context', phase: 2 },
      ],
      materializedFiles: [
        { filePath: 'src/routes/api.js', status: 'created' },
        { filePath: 'src/middleware/auth.js', status: 'created' },
        { filePath: 'tests/api.test.js', status: 'created' },
      ],
    };

    it('품질 게이트 결과 테이블을 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('품질 게이트 결과');
      expect(report).toContain('Critical');
      expect(report).toContain('Important');
      expect(report).toContain('통과');
    });

    it('리뷰 요약 섹션을 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('리뷰 요약');
      expect(report).toContain('qa');
    });

    it('실행 이력 섹션을 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('실행 이력');
    });

    it('journal에 fix가 있으면 fix 시도 횟수를 표시한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toMatch(/fix.*1회/i);
    });

    it('생성된 파일 목록 섹션을 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('생성된 파일');
      expect(report).toContain('src/routes/api.js');
      expect(report).toContain('src/middleware/auth.js');
    });

    it('CEO 체크리스트를 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('CEO 체크리스트');
      expect(report).toContain('[ ]');
    });

    it('실행 요약 헤더를 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('## [GoodVibe]');
      expect(report).toContain('팀 관리 웹앱');
      expect(report).toContain('plan-execute');
    });

    it('팀 정보를 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('cto');
      expect(report).toContain('backend');
      expect(report).toContain('qa');
    });

    it('executionState가 비어있어도 에러 없이 동작한다', () => {
      const report = buildMergeReport({ name: 'test', team: [] }, {});
      expect(report).toContain('[GoodVibe]');
      expect(report).toContain('Generated by good-vibe');
    });

    it('materializedFiles가 없어도 동작한다', () => {
      const stateNoFiles = { ...baseExecutionState, materializedFiles: undefined };
      const report = buildMergeReport(baseProject, stateNoFiles);
      expect(report).toContain('[GoodVibe]');
    });

    it('Generated by good-vibe 푸터를 포함한다', () => {
      const report = buildMergeReport(baseProject, baseExecutionState);
      expect(report).toContain('Generated by good-vibe');
    });
  });

  describe('finalizeWithPR', () => {
    it('github.enabled=false이면 skipped를 반환한다', async () => {
      const result = await finalizeWithPR('/tmp/proj', {
        project: { name: 'test', team: [] },
        executionState: { branchName: 'gv/test' },
        githubConfig: { enabled: false },
      });
      expect(result.pr.skipped).toBe(true);
      expect(result.pr.reason).toContain('비활성화');
    });

    it('branchName이 없으면 skipped를 반환한다', async () => {
      const result = await finalizeWithPR('/tmp/proj', {
        project: { name: 'test', team: [] },
        executionState: {},
        githubConfig: { enabled: true, baseBranch: 'main' },
      });
      expect(result.pr.skipped).toBe(true);
      expect(result.pr.reason).toContain('branch');
    });

    it('정상 흐름에서 push → PR 생성 → URL 반환', async () => {
      execFileSync
        .mockReturnValueOnce('origin\tgit@github.com:u/r.git (fetch)\n') // hasRemote: git remote -v (non-empty → has remote)
        .mockReturnValueOnce('') // pushBranch: git push -u origin
        .mockReturnValueOnce('https://github.com/user/repo/pull/99\n'); // createPullRequest: gh pr create

      const result = await finalizeWithPR('/tmp/proj', {
        project: {
          name: '팀 관리 웹앱',
          mode: 'plan-execute',
          team: [{ roleId: 'cto' }],
        },
        executionState: {
          branchName: 'gv/team-mgmt-20260303',
          completedPhases: [1],
          phaseResults: {},
        },
        githubConfig: {
          enabled: true,
          baseBranch: 'main',
          autoPush: true,
          autoCreatePR: true,
          prDraft: false,
        },
      });

      expect(result.pr.success).toBe(true);
      expect(result.pr.url).toBe('https://github.com/user/repo/pull/99');
    });

    it('gh 미설치 시 graceful skip', async () => {
      execFileSync.mockImplementation(() => {
        const err = new Error('gh not found');
        err.code = 'ENOENT';
        throw err;
      });

      const result = await finalizeWithPR('/tmp/proj', {
        project: { name: 'test', team: [] },
        executionState: { branchName: 'gv/test' },
        githubConfig: {
          enabled: true,
          baseBranch: 'main',
          autoPush: true,
          autoCreatePR: true,
          prDraft: false,
        },
      });

      expect(result.pr.skipped).toBe(true);
    });

    it('autoPush=false이면 push를 건너뛴다', async () => {
      execFileSync.mockReturnValueOnce('https://github.com/user/repo/pull/100\n');

      const result = await finalizeWithPR('/tmp/proj', {
        project: { name: 'test', mode: 'quick-build', team: [] },
        executionState: {
          branchName: 'gv/test',
          completedPhases: [],
          phaseResults: {},
        },
        githubConfig: {
          enabled: true,
          baseBranch: 'main',
          autoPush: false,
          autoCreatePR: true,
          prDraft: false,
        },
      });

      expect(result.pr.success).toBe(true);
    });

    it('autoCreatePR=false이면 PR 생성을 건너뛴다', async () => {
      execFileSync
        .mockReturnValueOnce('origin\tgit@github.com:u/r.git (fetch)') // git remote -v
        .mockReturnValueOnce(''); // git push

      const result = await finalizeWithPR('/tmp/proj', {
        project: { name: 'test', team: [] },
        executionState: { branchName: 'gv/test' },
        githubConfig: {
          enabled: true,
          baseBranch: 'main',
          autoPush: true,
          autoCreatePR: false,
          prDraft: false,
        },
      });

      expect(result.pr.skipped).toBe(true);
      expect(result.pr.reason).toContain('비활성화');
    });
  });
});
