import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  buildPRTitle,
  buildPRBody,
  buildPRLabels,
  createPullRequest,
} from '../scripts/lib/project/pr-manager.js';
import { execFileSync } from 'child_process';

vi.mock('child_process', () => ({
  execFileSync: vi.fn(),
}));

describe('pr-manager', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('buildPRTitle', () => {
    it('프로젝트명을 포함한 PR 제목을 생성한다', () => {
      const title = buildPRTitle({ name: '팀 관리 웹앱' });
      expect(title).toContain('팀 관리 웹앱');
      expect(title).toContain('[GoodVibe]');
    });

    it('커스텀 제목을 지정할 수 있다', () => {
      const title = buildPRTitle({ name: 'test' }, { customTitle: 'feat: add auth' });
      expect(title).toBe('feat: add auth');
    });

    it('70자 이하로 유지한다', () => {
      const title = buildPRTitle({ name: '매우 긴 프로젝트 이름인데 이것은 정말로 아주 매우 길어서 잘려야 합니다' });
      expect(title.length).toBeLessThanOrEqual(70);
    });
  });

  describe('buildPRBody', () => {
    it('프로젝트 요약을 포함한 마크다운을 생성한다', () => {
      const project = {
        name: '팀 관리 웹앱',
        mode: 'plan-execute',
        team: [
          { roleId: 'cto' },
          { roleId: 'backend' },
          { roleId: 'qa' },
        ],
      };
      const executionState = {
        completedPhases: [1, 2, 3],
        phaseResults: {
          1: { taskResults: [{}, {}], qualityGate: { criticalCount: 0, importantCount: 1 } },
          2: { taskResults: [{}], qualityGate: { criticalCount: 0, importantCount: 2 } },
          3: { taskResults: [{}, {}, {}], qualityGate: { criticalCount: 0, importantCount: 0 } },
        },
      };

      const body = buildPRBody(project, executionState);
      expect(body).toContain('## [GoodVibe]');
      expect(body).toContain('plan-execute');
      expect(body).toContain('3개 완료');
      expect(body).toContain('cto');
      expect(body).toContain('Generated by good-vibe-coding');
    });

    it('빈 Phase 결과에도 동작한다', () => {
      const project = { name: 'test', mode: 'quick-build', team: [] };
      const executionState = { completedPhases: [], phaseResults: {} };
      const body = buildPRBody(project, executionState);
      expect(body).toContain('[GoodVibe]');
    });

    it('executionState가 없어도 동작한다', () => {
      const body = buildPRBody({ name: 'test', mode: 'plan-only', team: [] });
      expect(body).toContain('[GoodVibe]');
    });
  });

  describe('buildPRLabels', () => {
    it('프로젝트 모드를 라벨에 포함한다', () => {
      const labels = buildPRLabels({ mode: 'plan-execute', type: 'web-app' });
      expect(labels).toContain('good-vibe');
      expect(labels).toContain('plan-execute');
    });

    it('프로젝트 타입을 라벨에 포함한다', () => {
      const labels = buildPRLabels({ mode: 'quick-build', type: 'telegram-bot' });
      expect(labels).toContain('telegram-bot');
    });

    it('빈 프로젝트에도 기본 라벨을 반환한다', () => {
      const labels = buildPRLabels({});
      expect(labels).toContain('good-vibe');
    });
  });

  describe('createPullRequest', () => {
    it('gh pr create를 실행하고 URL을 반환한다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/42\n');

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/my-branch',
        baseBranch: 'main',
        title: '[GoodVibe] 팀 관리 웹앱',
        body: '## Summary\n...',
      });

      expect(result.success).toBe(true);
      expect(result.url).toBe('https://github.com/user/repo/pull/42');
      expect(result.skipped).toBe(false);
    });

    it('draft PR을 생성할 수 있다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/43\n');

      createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
        draft: true,
      });

      expect(execFileSync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['--draft']),
        expect.any(Object)
      );
    });

    it('라벨을 포함할 수 있다', () => {
      execFileSync.mockReturnValue('https://github.com/user/repo/pull/44\n');

      createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
        labels: ['good-vibe', 'plan-execute'],
      });

      expect(execFileSync).toHaveBeenCalledWith(
        'gh',
        expect.arrayContaining(['--label', 'good-vibe,plan-execute']),
        expect.any(Object)
      );
    });

    it('gh 미설치 시 skipped를 반환한다', () => {
      execFileSync.mockImplementation(() => {
        const err = new Error('gh not found');
        err.code = 'ENOENT';
        throw err;
      });

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
      });

      expect(result.success).toBe(true);
      expect(result.skipped).toBe(true);
      expect(result.reason).toContain('gh');
    });

    it('기타 gh 에러 시 실패를 반환한다', () => {
      execFileSync.mockImplementation(() => {
        const err = new Error('permission denied');
        err.stderr = Buffer.from('not authorized');
        throw err;
      });

      const result = createPullRequest('/tmp/proj', {
        branchName: 'gv/branch',
        baseBranch: 'main',
        title: 'test',
        body: 'body',
      });

      expect(result.success).toBe(false);
      expect(result.skipped).toBe(false);
    });
  });
});
