/**
 * pr-manager — Pull Request 생성/관리
 *
 * 실행 완료 후 자동 PR 생성, PR URL을 project.json에 기록.
 * gh CLI가 없으면 graceful skip.
 */

import { execFileSync } from 'child_process';

const MAX_TITLE_LENGTH = 70;

/**
 * PR 제목을 생성한다 (pure).
 * @param {object} project - 프로젝트 객체
 * @param {object} [options={}]
 * @param {string} [options.customTitle] - 커스텀 제목
 * @returns {string}
 */
export function buildPRTitle(project, options = {}) {
  if (options.customTitle) return options.customTitle;

  const name = project.name || 'Untitled';
  const title = `[GoodVibe] ${name}`;

  if (title.length > MAX_TITLE_LENGTH) {
    return title.slice(0, MAX_TITLE_LENGTH - 3) + '...';
  }
  return title;
}

/**
 * PR 본문 마크다운을 생성한다 (pure).
 * @param {object} project - 프로젝트 객체
 * @param {object} [executionState] - 실행 상태
 * @returns {string}
 */
export function buildPRBody(project, executionState) {
  const name = project.name || 'Untitled';
  const mode = project.mode || 'unknown';
  const teamNames = (project.team || []).map(t => t.roleId || t.name || 'unknown');

  const lines = [
    `## [GoodVibe] ${name}`,
    '',
    '### 실행 요약',
    `- 모드: ${mode}`,
  ];

  if (executionState) {
    const completedCount = (executionState.completedPhases || []).length;
    lines.push(`- Phase: ${completedCount}개 완료`);
  }

  if (teamNames.length > 0) {
    lines.push(`- 팀: ${teamNames.join(', ')}`);
  }

  if (executionState && executionState.phaseResults) {
    const phases = Object.keys(executionState.phaseResults).sort((a, b) => a - b);
    if (phases.length > 0) {
      lines.push('');
      lines.push('### Phase 결과');
      lines.push('| Phase | 태스크 | Critical | Important |');
      lines.push('|-------|--------|----------|-----------|');

      for (const p of phases) {
        const pr = executionState.phaseResults[p];
        const taskCount = (pr.taskResults || []).length;
        const qg = pr.qualityGate || {};
        lines.push(`| ${p} | ${taskCount} | ${qg.criticalCount ?? '-'} | ${qg.importantCount ?? '-'} |`);
      }
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by good-vibe-coding');

  return lines.join('\n');
}

/**
 * PR 라벨을 결정한다 (pure).
 * @param {object} project
 * @returns {string[]}
 */
export function buildPRLabels(project) {
  const labels = ['good-vibe'];
  if (project.mode) labels.push(project.mode);
  if (project.type) labels.push(project.type);
  return labels;
}

/**
 * PR을 생성한다. gh CLI 미설치 시 graceful skip.
 * @param {string} projectDir
 * @param {object} options
 * @param {string} options.branchName
 * @param {string} options.baseBranch
 * @param {string} options.title
 * @param {string} options.body
 * @param {string[]} [options.labels]
 * @param {boolean} [options.draft=false]
 * @returns {{success: boolean, url: string|null, skipped: boolean, reason: string|null, error: string|null}}
 */
export function createPullRequest(projectDir, options = {}) {
  const { branchName, baseBranch = 'main', title, body, labels, draft = false } = options;

  const args = ['pr', 'create',
    '--head', branchName,
    '--base', baseBranch,
    '--title', title,
    '--body', body,
  ];

  if (draft) args.push('--draft');
  if (labels && labels.length > 0) args.push('--label', labels.join(','));

  try {
    const output = execFileSync('gh', args, {
      cwd: projectDir, stdio: 'pipe', encoding: 'utf-8',
    });

    const urlMatch = output.match(/(https:\/\/github\.com\/[^\s)]+)/);
    const url = urlMatch ? urlMatch[1].trim() : output.trim();

    return { success: true, url, skipped: false, reason: null, error: null };
  } catch (err) {
    if (err.code === 'ENOENT') {
      return { success: true, url: null, skipped: true, reason: 'gh CLI가 설치되지 않았습니다', error: null };
    }
    const message = err.stderr ? err.stderr.toString() : err.message;
    return { success: false, url: null, skipped: false, reason: null, error: message };
  }
}
