#!/usr/bin/env bash
# phase4-report.sh — UX 보고서 + 자동 머지 + 텔레그램 알림
# 오케스트레이터에서 source 해서 호출

# ── 안전 경로 체크 (자동 머지 허용 판정) ──────────────────
check_safe_paths() {
  local pr_number="$1"
  local safe_paths_str="${SAFE_PATHS:-commands/ guides/ templates/ presets/ agents/ skills/}"

  local changed_files
  changed_files=$(gh pr diff "$pr_number" --name-only 2>/dev/null || echo "")

  if [[ -z "$changed_files" ]]; then
    echo "false"
    return
  fi

  local IFS=$'\n'
  for file in $changed_files; do
    local is_safe=false
    for safe in $safe_paths_str; do
      if [[ "$file" == ${safe}* ]]; then
        is_safe=true
        break
      fi
    done
    # validators.js 에러 메시지만 허용
    if [[ "$file" == "scripts/lib/core/validators.js" ]]; then
      is_safe=true
    fi
    # output/*.js 포맷팅만 허용
    if [[ "$file" == scripts/lib/output/*.js ]]; then
      is_safe=true
    fi
    if [[ "$is_safe" == "false" ]]; then
      echo "false"
      return
    fi
  done

  echo "true"
}

run_phase4() {
  log_phase "Phase4" "=== UX 보고서 + 알림 시작 ==="

  local pr_number pr_url review_status fix_cycles run_date perspective_id perspective_name
  pr_number=$(read_file_or_default "${RUN_DIR}/pr-number" "")
  pr_url=$(read_file_or_default "${RUN_DIR}/pr-url" "")
  review_status=$(read_file_or_default "${RUN_DIR}/review-status" "UNKNOWN")
  fix_cycles=$(read_file_or_default "${RUN_DIR}/fix-cycle-count" "0")
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')
  perspective_id=$(grep PERSPECTIVE_ID "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || echo "unknown")
  perspective_name=$(jq -r '.name' "${RUN_DIR}/perspective.json" 2>/dev/null || echo "UX")

  # ── 메트릭 수집 ───────────────────────────────────────
  local issue_count=0
  if [[ -f "${RUN_DIR}/issues-created.txt" ]]; then
    issue_count=$(wc -l < "${RUN_DIR}/issues-created.txt" | tr -d ' ')
  fi

  local commit_count=0
  commit_count=$(git log "${BASE_BRANCH}..HEAD" --oneline 2>/dev/null | wc -l | tr -d ' ')

  local file_count=0
  file_count=$(git diff --name-only "${BASE_BRANCH}..HEAD" 2>/dev/null | wc -l | tr -d ' ')

  log_phase "Phase4" "메트릭: issues=${issue_count}, commits=${commit_count}, files=${file_count}, review=${review_status}"

  # ── 히스토리 기록 ─────────────────────────────────────
  local approved_val="null"
  case "$review_status" in
    APPROVED) approved_val="true" ;;
    CHANGES_REQUESTED) approved_val="false" ;;
  esac

  local total_rounds
  total_rounds=$(read_file_or_default "${RUN_DIR}/total-rounds" "1")
  local last_sla_score=""
  local i
  for i in $(seq "$total_rounds" -1 1); do
    last_sla_score=$(read_file_or_default "${RUN_DIR}/sla-score-round${i}" "")
    if [[ -n "$last_sla_score" ]]; then break; fi
  done

  local hist_stop_reason
  hist_stop_reason=$(read_file_or_default "${RUN_DIR}/stop-reason" "")

  # UX 히스토리에는 perspective 정보도 포함
  local history_entry
  history_entry=$(jq -nc \
    --arg date "$run_date" \
    --argjson issues "${issue_count:-0}" \
    --arg perspective "$perspective_id" \
    --argjson approved "${approved_val}" \
    --argjson fixCycles "${fix_cycles:-0}" \
    --arg prUrl "${pr_url:-null}" \
    --arg stopReason "${hist_stop_reason:-}" \
    --argjson totalRounds "${total_rounds:-1}" \
    --arg slaScore "${last_sla_score:-null}" \
    '{date: $date, issues: $issues, perspective: $perspective, categories: [], approved: $approved, fixCycles: $fixCycles, mergedAt: null, prUrl: (if $prUrl == "null" or $prUrl == "" then null else $prUrl end), stopReason: (if $stopReason == "" then null else $stopReason end), totalRounds: $totalRounds, slaScore: (if $slaScore == "null" or $slaScore == "" then null else ($slaScore | tonumber) end)}')

  mkdir -p "$(dirname "$HISTORY_FILE")"
  echo "$history_entry" >> "$HISTORY_FILE"
  log_phase "Phase4" "히스토리 기록 완료 (rounds=${total_rounds}, sla=${last_sla_score:-N/A})"

  # ── PR body 업데이트 + 자동 머지 ──────────────────────
  if [[ -n "$pr_number" ]]; then
    # SLA 대시보드 생성
    local sla_dashboard=""
    if [[ -f "${RUN_DIR}/round-metrics.jsonl" ]]; then
      sla_dashboard=$(node "${SCRIPT_DIR}/lib/ux-sla-evaluator.js" dashboard "${RUN_DIR}/round-metrics.jsonl" 2>/dev/null || echo "")
    fi

    # 생성된 이슈 목록 (closes 키워드로 자동 닫기)
    local issues_section=""
    if [[ -f "${RUN_DIR}/issues-created.txt" ]] && [[ -s "${RUN_DIR}/issues-created.txt" ]]; then
      issues_section=$'\n### 관련 이슈\n\n'
      while read -r num; do
        local issue_title
        issue_title=$(gh issue view "$num" --json title --jq '.title' 2>/dev/null || echo "제목 조회 실패")
        issues_section+="- closes #${num} ${issue_title}"$'\n'
      done < "${RUN_DIR}/issues-created.txt"
    fi

    local pr_body
    pr_body=$(cat <<BODY_EOF
## UX Improvement 결과

**관점**: ${perspective_name} (${perspective_id})
**날짜**: ${run_date}

### 개선 요약

> ${issue_count}건의 UX 개선점을 발견하고, ${file_count}개 파일을 수정했습니다.
${issues_section}
${sla_dashboard}

---

- [ ] 수정 내용 확인
- [ ] 머지 승인

Generated by UX Improvement Pipeline
BODY_EOF
)

    gh pr edit "$pr_number" --body "$pr_body" >> "$LOG_FILE" 2>&1 || true

    # ── 자동 머지 판정 ─────────────────────────────────
    if [[ "$review_status" == "APPROVED" ]]; then
      gh pr edit "$pr_number" --add-label "merge-ready" >> "$LOG_FILE" 2>&1 || true

      if [[ "${AUTO_MERGE:-false}" == "true" ]]; then
        local is_safe
        is_safe=$(check_safe_paths "$pr_number")

        if [[ "$is_safe" == "true" ]]; then
          log_phase "Phase4" "안전 경로만 변경됨 — 자동 머지 시도 (squash)..."
          if gh pr merge "$pr_number" --squash --delete-branch >> "$LOG_FILE" 2>&1; then
            log_phase "Phase4" "자동 머지 완료"
          else
            log_phase "Phase4" "자동 머지 실패 — 수동 확인 필요"
          fi
        else
          log_phase "Phase4" "코어 파일 변경 포함 — 자동 머지 건너뜀 (CEO 수동 머지 대기)"
        fi
      fi
    fi
  fi

  # ── 텔레그램 알림 ─────────────────────────────────────
  local sla_info=""
  if [[ -n "$last_sla_score" ]]; then
    sla_info=" (UX SLA: ${last_sla_score}/10)"
  fi

  case "$review_status" in
    APPROVED)
      send_telegram "" "UX 개선이 완료되었습니다!

관점: ${perspective_name}
${issue_count}건 발견, ${file_count}개 파일 수정${sla_info}

${pr_url}"
      ;;
    CHANGES_REQUESTED)
      send_telegram "" "UX 개선 결과를 알려드려요.

관점: ${perspective_name}
일부 수정이 완벽하지 않아 확인이 필요합니다.

${pr_url}"
      ;;
    *)
      send_telegram "" "UX 개선 결과: ${perspective_name}
${issue_count}건 발견, ${file_count}개 파일 수정${sla_info}

${pr_url}"
      ;;
  esac

  log_phase "Phase4" "=== UX 보고서 + 알림 완료 ==="
  return 0
}

# ── 발견 없음 시 정리 ──────────────────────────────────────
run_phase4_no_findings() {
  log_phase "Phase4" "=== UX 발견 없음 정리 ==="

  local run_date
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')
  local perspective_id
  perspective_id=$(grep PERSPECTIVE_ID "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || echo "unknown")

  # 히스토리에 빈 실행 기록
  local history_entry
  history_entry=$(jq -nc \
    --arg date "$run_date" \
    --arg perspective "$perspective_id" \
    '{date: $date, issues: 0, perspective: $perspective, categories: [], approved: null, fixCycles: 0, mergedAt: null, prUrl: null, stopReason: null, totalRounds: 1, slaScore: null}')
  mkdir -p "$(dirname "$HISTORY_FILE")"
  echo "$history_entry" >> "$HISTORY_FILE"

  # 브랜치 삭제
  if [[ -n "${BRANCH_NAME:-}" ]]; then
    log_phase "Phase4" "발견 없음 — 브랜치 삭제: ${BRANCH_NAME}"
    delete_branch "$BRANCH_NAME" 2>/dev/null || true
  fi

  send_telegram "" "UX 점검: 추가로 개선할 점을 찾지 못했어요.
현재 UX 상태가 양호합니다!"

  log_phase "Phase4" "=== UX 발견 없음 정리 완료 ==="
}

# ── 에러 시 정리 ────────────────────────────────────────
run_phase4_error() {
  local error_msg="${1:-알 수 없는 에러}"
  log_phase "Phase4" "=== UX 에러 정리: ${error_msg} ==="

  local run_date
  run_date=$(grep RUN_DATE "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || date '+%Y-%m-%d')
  local perspective_id
  perspective_id=$(grep PERSPECTIVE_ID "${RUN_DIR}/meta.env" 2>/dev/null | cut -d= -f2 || echo "unknown")

  local history_entry
  history_entry=$(jq -nc \
    --arg date "$run_date" \
    --arg perspective "$perspective_id" \
    '{date: $date, issues: 0, perspective: $perspective, categories: [], approved: null, fixCycles: 0, mergedAt: null, prUrl: null, stopReason: null, totalRounds: 1, slaScore: null}')
  mkdir -p "$(dirname "$HISTORY_FILE")"
  echo "$history_entry" >> "$HISTORY_FILE"

  send_telegram "" "UX 점검 중 문제가 생겼어요.
다음 점검 때 자동으로 다시 시도합니다."

  log_phase "Phase4" "=== UX 에러 정리 완료 ==="
}
